[build]
    publish = '11ty-output'

[dev]
  targetPort = 8080
  command = "npx @11ty/eleventy --watch --serve"

[[edge_functions]]
  path = "/login"
  function = "auth-login-1-start"

[[edge_functions]]
  path = "/auth-redirect"
  function = "auth-login-2-redirect-to-spotify"

[[edge_functions]]
  path = "/callback"
  function = "auth-login-3-callback"

[[edge_functions]]
  path = "/app"
  function = "auth-redirect-if-no-cookie"

[[edge_functions]]
  path = "/auth-check"
  function = "spotify-check-registered"

[[edge_functions]]
  path = "/logout"
  function = "auth-logout"

[[edge_functions]]
  path = "/create-playlist"
  function = "spotify-create-playlist"

[[edge_functions]]
  path = "/top-genres"
  function = "spotify-get-top-genres"


[[edge_functions]]
  path = "/artists-for-genre"
  function = "enao-get-artists-for-genre"

[[edge_functions]]
  path = "/list-playlists-to-include"
  function = "spotify-prepare-playlist-info"

[[edge_functions]]
  path = "/playlists-for-genre"
  function = "spotify-playlists-for-genre"

[[edge_functions]]
  path = "/spotify-similar-genres"
  function = "spotify-similar-genres"

[[edge_functions]]
  path = "/spotify-artist"
  function = "spotify-lookup-artist"

[[edge_functions]]
  path = "/spotify-search"
  function = "spotify-search"

[[redirects]]
  from = "/similar-genres/*"
  to = "/.netlify/builders/enao-get-similar-genres"
  status = 200

[[redirects]]
  from = "/app/"
  to = "/app/1-explore/"
  status = 200